//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffe_Grinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int AlertID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
