//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffe_Grinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoffeeInventory()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int CoffeeID { get; set; }
        public Nullable<int> CoffeeTypeID { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<decimal> PricePerKg { get; set; }
        public string CoffeeName { get; set; }
        public string Description { get; set; }
    
        public virtual CoffeeType CoffeeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
