//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffe_Grinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CoffeeInventoryWithTypes
    {
        public int CoffeeID { get; set; }
        public string CoffeeName { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<decimal> PricePerKg { get; set; }
        public string Description { get; set; }
    }
}
