//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffe_Grinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderDetailsExtended
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CustomerName { get; set; }
        public string StatusName { get; set; }
        public string CoffeeName { get; set; }
        public string CoffeeType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
    }
}
